### ISSUE TITLE
Cost of Morgulis is incorrect

### ISSUE THREAD

**Issue by drekryan** [Beskhue/ClickerHeroesCalculator#10]
At least for the beginning levels of Morgulis the Ancient of Death the cost to level him alternates between 1HS and 2HS. i.e. level one costs 1HS, level 2 is 2HS, level 3 is 1HS. I dont know if this levels out to 1HS 100% of the time after so many levels but because the beginning cost to level this ancient alternates and the calculator always assumes every level costs 1HS this causes the calculator to recommend you level him more than you have the HS to.

**Comment by tomcur** [comment]
Thank you for your report. Morgulis' cost indeed is slightly buggy in-game. It levels out to the correct cost, though.

Note that if you own the outsider Chor'gorloth, and if you buy more than one level in Morgulis in bulk, it actually costs less than 1 HS per level. The calculator takes this into account, and it is correct.
