### ISSUE TITLE
New version not showing Transcendent Level Cap 

### ISSUE THREAD

**Issue by shittiidavincii** [Beskhue/ClickerHeroesCalculator#13]
First of all, love the calculator, thanks for your hard work. I use it...every ascension. 

However, your new version that you pushed today(?) doesn't show the Transcendent Power Level Cap in the "Outsider" tab anymore. I really liked it as it'd show where you would sort of "plateau" for that transcension, and I liked seeing its progress as I levelled Solomon and Atman. 

Can you bring it back? 

Thanks!

**Comment by tomcur** [comment]
Hi there,

In the new Clicker Heroes version (1.0e10) there no longer is a transcendent soul cap, and so there is no longer a zone at which it will max out.

Additionally, the cap was based on Solomon's level, but Solomon is no longer available once transcended.

Unfortunately, I had to remove it.
