### ISSUE TITLE
Not enough HS to level Vaagur as a last one

### ISSUE THREAD

**Issue by Gamesiarz** [Beskhue/ClickerHeroesCalculator#16]
Hello,
I have a problem. I'm using active build with "1" set to Level Revolc and Level skill ancients. Calculator precision is set to max 35 also "Best hero will be leveled beyond 8,000" is checked. When I try to level like it should be according to calculator I was able to level my Vaagur as a last to 130 instead 134. Here's my save

`7a990d405d2c6fb93aa8fbb0ec1a3b23eNrtXVmTGzeS/iuKfvYwcB9+Wql1ecY63C2NN+bFUU1C3RVis+gqUnLbof++mUAV6kJVsw+uYmPdE6GhyQLyQyaQF7KAv062+3J5lVXuzC2LcnXy41/ffjipPufr9cvSudN1vvxcnfxI4LurYr9enV8VX1+7sni+hW935d79cHKVX165avc6r3ZFmS+fbpa52+zgZ2Z/OCndl7zKi83Jj5v9eg0PZ9U/i3zjVq/2+RqofcrWFfRR7HdVvnIltPrr5Lflviyhi4/5qmra9R6g+M/afXFrjyyHfigA3EKbmvo5YA2w9/5XGBPrNBKhEUs2ok0rBq14pxWrm/FkM/zVN+PQTIwRilmEAhrJTiNa05ITEGXdTkI71WmnQjOVhkjrVgpa6U4rGVrpNLGGloZWptOKh1Ym2UrVjQw0suNGdraRhUaUjAWGopmTGCXfvkHTbLmDKfcsK8Ns3sK0KTbZ+jxbOz9/Kpe1X7zYZBdrt2pm828VfPlis/qQX8Okzq63KAvFuCLGAJlP66y66rerp/Bv66y8hCbv6/X0bL9Zrd1PKy/j3zb762aB1DBQcqt85VfYu82HMttUS7dZuc3SfcguGjh+JcJie7Nf7/LtOneln+ttw2a5Ddu0qxcG4zG0bd64Ekhl5c0soaZdoyBWr2DFAnBOcFlX2wLArj4U5/vyi7vpdXNa5rt8ma09udOrDIbke3J/7MrM9/L0a1aukHnY2WWBmuBELDTjFP60FoRLSZ2iJ9M9jocFumnrR1RLZNfydNfD9woIPis2+7D+PgGnzmA8bhn+u9xf5Cggyszw+YYmSPPClc/zarvObt4UK9d0X7ps9T7bLa/e+idgVHRBHEzlhsHFHiZNRNhh44vrLF+fu9/3bv2+LK63EXFenV65bIedNa32Fzd+yDgBqw9XefUUhxnULKkp/QpsfuUZC99c76t8OZywq6z8fJbv9jVXq3HbZrjr/JPbwXp4PmqhBejQZbFeu+XOrZ4ur3JYr9dB/UdD4h8eTOCrejGc1cwm3jScO7d5676iIH/auetoYr7ACvaj0+kuG6BZHwAaitABaz7w5oNoPsjmg2o+6OaDaT7Y5gMqpfpT7JvGzmnsncbuaeyfRgI0UqCRBI00WKTBWvyRBos0WKTBIg0WabBIg0UaLNLgkQaPNHjLpEiDRxo80uCRBo80eKTBIw0RaYhIQ0QaopVEpCEiDRFpiEhDRBoi0pCRhow0ZKQhIw3ZijvSkJGGjDRkpCEjDRVpqEhDRRoq0lCRhmrnVKShIg0VaahIQ0caOtLQkYaONHSkoSMN3U7cSENHGjrSMJGGiTRMpGEiDRNpmEjDRBqmXR2Rhok0bKRhIw0badjYs40929izjT3bduF1Vl679Ei79ki7+Ei75ki76Ei7wjrLs7M+O0uwXYO0XYS0XXG0XXK0XXO0XS60XS+Udx5oSbRTnLZznLaTnIrOsy2cdp7TdqLTdqbTdqpT2dE9LbV2ttN2QtNmRn+LbvzLfJNXV271n2Lj0KEClwxcnt05at2PlQt69goigNOg9b1a/uvkOvvjPP8TWjAJLfoe/F/+ee/zoCPe/EfjxxfLzx2r1DrN++1lma3A6Fxnl65rPk7QLVilv65jAbfNlz+3PfVjgEcnyJIE2/Dh0QnyJME28Hh0giJJsA1aHp2gTBJso51HJ6iSBNtAKUmQWinnaDKSJsoW2mhpOSxxQxXnRjuwgjEISwBpY69HH7lJEmzjtkcnaJMEOzHf42sEklYJ5Ftw5I5Cc0INoR6iR1JENK2JKKoieiRdRNPKiKI2okdSRzStjygqJHokjUTTKomiTqIzSokSLe9DdkENkZYqRjTVgnLlIAiooaSVFUVtRfWRhp/WSxQVEz2SZqJp1URRN9EjKSea1k4U1RM7knpiafXEUD2xI6kn1ldPTWaQeTfpWH7ShKOE6okdST2xtHpiqJ7YkdQTS6snhuqJHUk9sbR6Yqie2JF8JpbWQwz1EDuSHmJpPcRQD7Ej6SGW1kMM9RDr6aEQVj0GybQaYqiGODkKSZ7WQhy1EKfHIZn2kTgqIc6OQzKtg7iP1vhxSE6Ea6iCuDgOybQG4qiBuDwOybQC4qiAuDoOybT+4ah/uD4OybT64ah+uDkOybT24ah9+HG0D09rH47aRxxH+4i09hGofcRxtI8YuEDcNFu4AhWQOI4CEmkFJFABieMoIJFWQMInjI6jgMRExggVkDiOAhJpBSRQAYnjKCCRVkACFZA4jgISaQUkUAGJ4yggkVZAAhWQOI4CEmkFJFAByeMoIJlWQDKUFNTd+rR1u1E2v9FD8cHaC6VExc+qs+PQZvDbTcG5bbp0ov497o9WO9RhSmJphVsWm9WH4udR5n5dXOabf2frfJXtWvZtS9fdLH+d3ArQFjTXRVa55PY+qJg9EPHUYtXONuCCLv+dhdKdbL3+d17ts/WLT5/ccld1EKyLbPV0Fb+5WBfF9rTIN7jNTH390ddnRVU9d59ctnvt1tvmyc9ZeZ01NUpfvfwoId0nVvmqKcvwAEc0znDjvdo9LzYZ7mh0ij/qXt+X+XW2RvqDfj8Outx+veg+gW2x4sGtsGpq0Pbd1vmihTgzLqD/l1m+3pfubbHLPwGXEc6wRgU7xf3xRHdNYcyydG4T+8UKi7kO68bvNut8486zL7GeYVlAy+LrZq7xRU8ofdZBx1gx1qtueeu+VhHZdVOKMkcBePprXdvwCebVYHAb98fuDGZzKJtA+qFsBUvPin0Fa+M6g3nVBwZdvl9nN87HVByLD9br4it0i9U5z/Y3Va+PF1+w5ijRx+m6qBwuPGYZYYqgdl5elTDnr7Mq2dWbLN+EAQz683VLy2KPtSph9SzrddYrnWgLJXBZwjz/kG+bBtnqFPrK8stYblfvw+Gjrx2s6p3PR/5w8rUoQ4lHXQYTns6rDwAHZnSZrKFJq4WgcXbFrq0KoYZQZSzF5i6rYDafYsPqX7BOnHevhDIGNxZ38PUzrAT8GRa/8+lxiuM4czuspmql6fsP9SwnfMGYUZpKo4llijLlLEU1jjuLdUkYPCQUp8yC4lWcCBBN2GJp+8bSrFpNZfnqZVGe7S9uuryuF9suC8UkDSuwEiVsX9Jmb9MTfZVhXSOQtguhuTLCKEokTArmKO9sCmz21087/fhkbqg3w2wySNRSBcPS4EFlfXqqR+8chgHyPDELwZQS2hhmhBLWBnJTfXaH8VMNKfbpC2lmB6CiAUL5w8Io0d/BdEWFeDokibaCS2JiTn6EXC8IPKeoUtSCiFK4607kQbj7nJAd1DKFWqghamItE1xYmL7fvh00UGE4rABgrrUkbuyMp4RcWGmIBQFA7/gXasKaPZvhlCADNlgptVbW8OGUIEm+kiEbqQLGCEFsgo1sxEYJTl3ARhI8oOgoDWVdTy/Z7LGPIIU+B6AMygqDk0NAMcUWtv0z7d77GKKRI4g1C/z2G09DZGo0/6iWRsEUNQdhpAtiiREtSOFku2M/ggk6KQEzMEU2e/kjmBNE+rANARVJpDgYNihJFnuUTrX7/mPuEprAHRilaVMSkMTdo8I9lR5ukABVUjF+KG5KudXG6bZqIDVfE3BrBqmmoCAF13euG7jaU+nBhcVMJDX2MLhswRkTWmnrTFt0MMLLCB8vsIYxuqlHGOEd9N7DKcEOakGIOBAnNYaDdlS1rMC8trUJY7xghkd4G86opmwhgbehwt1INVgJ84RpTg9TDa1y5QPlahKAOdiUEeCGRbopexirhzSVhJ7WmJe8G+6hUbAJ3D4I6qNu+CRi7cQcbDEP25uXEYEwIHsX8DRlNkiKJUkjm5RPdGBiJcPYyNKFZEwqwAQ6QTNqHLWdIoVbjCwlhoH2Ba/ynkYWfAf4n2B0gouev0MuSkFA08Q/Kucsr0mZIT5tc1OdDyBrxYyWLNVvQt8aKakGWUTLo+esMLUJVtRMEpNmeIJKX1REgnamuM5G/YcRqRF6taCMW0I4lcGBiFotZZsZ02qC2WmzPOpejtQazmLLJJcjexQHZBPamFmitbTSch3YQdmMdQZnmUwAlxOKuCVgQt990BDYgsrDXYgR6DAcnQBtCDeGwmIS4E1rqV2c2UlX3JgpbqsJ0GkCA+QaJpImaow8jEmkQh9Yp8RA8KrBPwB+qBlTLZWcWpFpI53svY+Z+4g23W9iRYIAFINQDQJgQsEUOGpmbLViNMWMwCYzaaunyAzVJ8Rw8Hcg8kldnbLZENXZMfDAK8UmbfYElbHa1/Zgjk/itmmrNwRds8lOm+yDUQdj9TDUU8Z6DBu5pGjSZKfE01q9WAg4NtlqQQwHXJQoAW4GKE0mOjV+Q5PNBlwAn00L8OXV/Uw2jEoYiAO0TnBRjC2IssR2Y9AZW80ITfMQZYYMSRuRBIU+YFiAXAvLDgLMFuCiAXu0iBEHTUZISibABtaYSfei7b32L7gbKwWL+hfs+UF4wfRrzrWiEswKRJOYeGIzHgZnVI+B1yyScx5GkkwPOaWCcVysByJX0uJcN17AQL21HCn3QlieYHnNLDET+6fJ9JEzaiWoc3kQcrGAqSqlAXuowY7KjgVJuRfSirEFaXg17WRMUBng1oYZb5QPm9saAi0FLoh/ORfrY8mMi6E0ao8h8JpVZsbRSJPpIwf3SMLIDlMjckGEJIb43ALXkjtGZ5wMzbRIAA+8mnY1Jqj01SdE6DCT5KEzRQoBohNAF1Osoi1ITvkaWqmxy1hzypBJX2OCSh83E1ooq8dLqBnR2I/mC6BqBSwLy4hS2jE+428YIpIqdtLTSHc/MFaEasEIH6Oux2MTegVGxATMUQgruJDgeUUDaZO5OWUncE86G30KPBAYmVlGxYEaZc6mp0ylkWY8wRtmqfiGRiLiStJJOAiKmQcjpwe5SQ2n7Hgv4O6wvV/zQNjsYNjAJp5OyCQF1HNmZNq7I53tl6ErNx4xqCkfZd7LkwvtqU6ZazniGJnLsogJ9hifHKR3wePHcwc8B08yP1aelNZt+FVaVnqhQA+Ab2EF+IPUGsdsZ8/vNk8cWqBZv2/yjHJCKDpFKa2rEmqRQzhqnZz1wKc4x30dI51Qh23PfYDe4HKmDgLos9sQVwsRt1TsnAeuzTi8bVgiZjzwJJU+bnDLwJBSchBuuQCqFvdBIcrHlKGjdMYBZ5okcNecstM7bWkqA9ygXayh7EB+g1jB+BLwlqSUjPJb/G8lx95gw6pp/3uKTA+5UIYTdShyurDgX1IODQjT3Hbc2JT/DetMJoAHXqmZzbcklT5uzYxVRIgDcUPwBLGWIBLWFANxth5Vyv+GiGusmBpWzW3DDcikPCspQdFSow9dmwSwSAI+FxWcYDDC5IwDDt5RAnnNLDOzIZcm00cO8rRgSMmhag+su1QKHH+lCfTumJ5xwY1NpJobZtmZdF+aTF/hQxhHCZeHzhYjjAE3BYYrDJEU3Hoz439bkVAsDbPm8n0DMiqQGZgqbnAbemwemjHphIsljIbQlDDgCkSSTLb4U364VWlDMe2HjygkkcMqJlYlkNdjGjuHQ7uO63Q290cJpWIKO52o40n6DgkHQQqdwB5GxW7F3vVJ6IF7jGraEz8ctvdrErBhQJLeCTY7GPa3adnMeTX6Fldc3+qKK0YY2HCsQriXKxfaKzHFMp2Izmcd8lREewdXvDOeIZ6AVJK7OuQJON8mkE+wwMTXpmdkZQ6SlVJamQfISimppnjjuXYHWaV4Y+4mqno4CTgIlD1YVCYpqhkGxJfNZyRlD5KUpsKwB0hK00RpRGSafbCk7N0kVQ8nAQeAGvpgSdk7SMozIL6iPy0pRg6RFKeS0wfoP2hPtJlgjUjUgcxJKlFd5k8GoHeB44czhoNAzYPXFMD5lgY+xYB4sMGMpOghkhLgXGP92X0lBe3ZuGInMo0+dE358xToXeAIo1NwPFDxYEnRw9dUYEA8DmJGUuwQSSmLBfn3lxS0F4xPsEZgadQDJcXuJKlmOGM4Hqh8sKTY4ZIKDIiHaIwlxRfaQJQNTqnGbQotHbed8zFuS+5pCPMYNw9YZ0oKIxiZYJdn5Hi/hkk5n+KjqR0JvwtJpzZpYp8DgAa99XHZeISeqt40mkhgflNdF4vhUhJOJifYTO1esvc+aIgWAfS4CC4Ox6R2TS3BDTjGlMFu+fwOOzzFJ3Dzqf3SPoHE1roSAqIDmYhkmiGZRAJBE6G1NcrC/xul2wqWVH5PMiMmcE/trCf77+MGZ1BapRIuWD0inXolhXP4STKI0AyHyRf3ZlLpPS1SBQczG+uD/lViM0lZiDqISKSC6gFpngphIYY1KEFlrVS2k+9IZfcsoVO41VTsnSQwQI717CRlEOsxpbJ7goBGYaDrKOZzuXCczWT3KOFKT0CfSuylKfRVJpEwm2QiWVsPypLEBjuAIbB0LMFULTOOy5nsHq7zqUk+tbfeJ6ADgT5w9Ai1ZGOtEoakiEroapCklbhbD3OKGO64nknuUbAldgL41O56kkAfOBPAVSbHk6UeUiKUVQusqVWSSWuYhpjF8bmsHmW+siBtcabSen0KgcDQunJ8mXEcLzRDSlUzDAw6by16OqvHKZ+aLHTKWiadhoRnoFiC6WFUlt2OvQP9UOeIT2f1DodtTBI2DigxV+Zgs4Nhf5uWzZRrFA8qm/HAxa0eOAxMKRixuKcPF9qnynAbZj7cAxeHe+Cd4YzhIFD54PwDwDnMA48MiMe7pTxwEKXFKcetBculRHviKxuXR5j+cBnRhnNwau5b6GosvrZEBZ1gl9EyZUnBwNzigad2rvyZc3TKdsY+ewDBgeBYG5UyxTLhDVKFiQt82aFTejrpfCf2ehqOTO+uTxAZwAbBaMXlgbDBLQX/mIMg4R/lqJirbvXcGMCu+eSPRZqqbk0R6aMGjYPvVJkDUUvNGLVGw9yl4KrZtvAv6Xub8QuXkVFmxgNPk+kjNxQsvNdCByCH2aapwYpT8Ks1BBaq3YlJed+GJ9yemln+rOCpN2jSZAbINdYLJHJN9ZgkSwQPkuDbhIzgpiS4Ta1DKNPFf2xqOU4dHZAk0Fc9yjJrTKLstxmSSAD3tczQN2MGy9KcIHM+OOPaTgDXE8CTBBI6k9jRZIxDSvlVAzXdO5c7YbmVnAJuJryTtB1Ians9Rl6PSd+OvGNgzIEGT064J+FMoQm7gW3qY0Y619D83xt6HMWHzm9/G/O/jfnfxvxvY/63Mf/bmP9/MebNkWx5OO3QH4z3brurjRQ84L85w+t/8IJFtHYfK3+7D/OvWjt/r5/QTBLtVYQnduaW5T5vD/RCKok+fDI2dAE6jRGr/Gm+A0zeUG6vyqxyYJpOgDObDPs9ee3WbnMSriz6BWHikWFnDm8b/GV3E673g17wI8yk0AMYjJNXxe7J6qYC6+/Km8UJHmq32Vc/51/qu+lif+f75dJVVbzUcGHxnDbnj637ZZ9vt51T+tbFrr7+ES/P+1A8z/GcRGo0FsEFJrpqv94NKAynt6GgUvxrH1n1cYvnNo6vocG7FbcO2FOjUoO/Tv/P92UWbm0Ce0n8iZnY5+mV6x6oWY5F41M/XjIarBEWeGMWLvYbuPzhZuvCNX27zI9e1vxx7YFZigMHOMEMzaC1l5HfI67C+WyxIiUl7KfrHEZ7kLBZV9j/ynGkT3ZX7snFHj7uHlngtCdwPFdG3lHesJLsjLz1SNxCgipp/jAb+3Bx07iWqbUKD2o7RNx0IG5/vgAekSSpuV3cqvHfUuL+cIMQDxI37Yr716x6kl9fF+UuW8Ov/1jiWY9uc+lWjyx31pO7ooRjEdRdBE9MeAlwSvD+Yome5Cnti/5RVrqKogfnlFsipa8DuU32bLTU8RpXzdEhul32NB4JkxL+23xZrN09pP8C8GyeXNw8yZ5cwngfWeS8J3KqqD/O7k4i1/71gkmR85HIDZUWPKXmjz+GxP2rtF7iBt0Bwxi9x2IXWitQ74wT3Pa5TeDxNZuUvJ+BKHfZ5uYwifP/TfUu+suc4FbNHfU70XR2mcuhzK2kuMFQ/2nzKKucRAVPMSyyUh0idD5a5VRDuMGppuR2oXsPM3XBOzDjFYhn827jXvoLmb27GA+9zoa3pvsDYc8cuAAVPOugKU5e9Kyy/a5Y4km0rjz/nG+6FwF/6xwki/cmvwqTjS4w2hJ4oCwMBQJu50+C7NL8gM3QFOIBv+ts4w8PLt8C+4IM881l51bnLiqk008pKdpmzPpYa98BJ20VjuzGJeEhvx6dbWsZxQ1pfOc3RAe7HFZMOPg8xhBaaSkhKuT4Lkw4AHeLx9uunv98Grx5lNgrPIL3LNt8DvOxF70IjsfndktEzrNliWc1D0rLDBX+UCO/LVoHHvWJvXQBEZqCeAdPBRQKQzzrj4vzQ/tXODLcckyH4L1nuHXMG/fwLMt7l7H793TAIzEafeI8XBP9V1jgGOekggrWxhTUcnzdBOOSmHzzd02n2ul2iRgJoZpW/iUL9ztoBrxk+hxUQuU1wmXRZj+xu/Za+MFVqDVg/xJTFZr76YmrkQVXHowgFuuIuiaxytZfQKTvi9zfag0hIf56iSKbAk5a+y2FUmCDEXbkVShnz3Gi/FRfD1Gfb38azp8mtcLk9WH4J/6dO/+VeJ5XuzK/2O+a68b916gmaF0KGhbVaZlfV8Xmyas96IEnxacnr0qE1Hmehduc9k0FffyBhy31QK+BQJqmrI8AfYvYUrSIaP8xcEObQfV/8Aa01rt4aE9o3FDFC4ZhmnolCCtgfX3SCyry6q372jm+HeE1TeWCcYkZRyOYFOACn3wLl0l3WI8O3S2sV2KC9Vgl1+O9jrw/y66fnG9zgImMP7/KVsXXasB65Hi445T0WW+HnPclKynWG9tnvU6zngmSZr0SkfWCj1ivFwwsmsKD8fCAOqpbQWTX+7XbnfRcvnlRCCUgDMMzqUC9c30Sy5qjKLCO8hZRkAMXQSuI8y0Y/6yzCCZkIeJVeH1ZkENXgaSHrQI5IQoytwjUglM8aBRT0RRfZZ1cErfJgSLjpeivAf5YjKddxvvZ/8xlq8rz3ZvOAdd5c8eHuCfX6XAFkKkVwG5je3oBcH/oGgQVeNoNu/8CUAvNjcbDBAw6agoWgN+3Q9fjOkuZEKpZm4kzlFuulPnWcUZ815Xf2cA3ZZa7/AsgqSWIp0kqDYPeb/I/+tabeTeAEBSW7+xjvFqFhRrxHThFZZ6tn5Zl8TWE1f52ARhp5UNSYIhYCG2tsJLgNhreb/FyXYDrUlbA4PryiOYKA2yMN3fUfgYeniTDkRboW4Brt8puWp8y3PQR7yrQoDlYPU+Cp7pyF/vW2VuGa9DdCvsKTu9zvNYAmQlLSf+D0n80F7rgPTKbYus2bnVac/596TDrGGz2dVHtwh0K78Ef9He4oOGS6IoCKCDS8RfjRSlRiPuL3FUvstJvUnLOao8Qp2Z9QQf+gD6fTxaDaup7oG+KVbz4w0NBhneQCGK7WPwE+Lhtr3Cpb1h5nVVXrk4VL7PN6uY02/h44we8Jf45NkCP22LZFPhxVoOSpw7m5Um48gJU5Gc3vPHkBgKhFbrr5678Aq5ne4MIBBbofcdAwg/m/OV/D6848X7x5CRpgTYMpHUI+zTckdG/+sPPlDdtUvrZHv6tr23c52PqgPDmTbGpdl5uNU13neW4OC9hWFWelX/+1yV+s1gW1ydjEmfuSwhy0EbUN4W0V1hc5Svno6H3xXbfyqQOYV5sduXNef5ne38R9f4l9btgGPXhCvJxW3VaXG9Bt7j6GjjPThzLeFD+LiD8uYk5KEQC9cZdjyIm8MPgx534YGlEmWK2sIIhrtq7YJoYGWQS1qifgE3IXf+aV8+yzabz+MX+5sUfoJ1+2WebnVeV8VqPSwdfrjvf4fVPCVXIICCJGTGDRxNjRASDKva7CvheDgfbBHe1TnxXwjNv99cX2G9944gfQPjuFegDCOGLQUZGSRsVsEGamFWp47X3gB1vTAlxWqOWvrzKP+1qCNBP81AbYtcB3JjbqtWxboWLvl7KcXqBGv997631CQVL5Q991IZDuOfPxbN45AsEoxbDhCr74t6V+SWGsyfbJX6DFySNqIqapnyTb/Y7F34Pl62GuQ/B3M05aMvgEWyzqvpalCtUL9Dx7y+fP/99DQ7isz++vP7PxSeMbNdr0C6923LQvMKob/7pNpgKaJYpqec1PP7er7BdvKPnZ7wgK22xQuwPzQYkcO10v2ILyzA+bbd1m2V846dsXREggiyHcsTc0jrbNnFco1XhGdDlL/EOnxd/bOM2Wrm/uBnLE0tDGjXdqp36tqxic/lTnVnILrLVqtgMxhPvZGqMeWvem9URoFY+GxAk5H0kmNZfgObT1XW+eeOqCmZgOx9hqr/79KF/iQ6TUUd51VQ6TFSdD/vtPjJ9X6G/yq3hV784xEpfEFxhn91MCm0LCMIFc01dwGMRYO0Wf3A1m83kCQILbjjmXDBYIRD18HBQz92I6oXGkhGwr5oKpQltS9VNjcM071p8JxxN8Nkeg/ydgNB4wzuJr0JMQPGH4NxR/AsIXBXDk47C0ZSifcOENneu+80VyuYoq7vPbGCcNOA8ak4JOMpYDmI67ysEyixepzBF2XSPIwaP+85A5EIKDgEQw6uVtNWdd2xiAEbbM6IfmfdSGyOF4nisbodws97DyZhzK34hmWHS4LmOqNO5uc/8swv//pRgVHNFtO1Mv0YxUBkP50sjYQuOu2lSEoqDAacklMncdVpYwrggEFIKIRlnbTEPbvgGKCoeJDMlDda5VgL+7j4rDL7/Rw23YFzhH8DBVeeImoBDx0NSpnDIOxNWaJwJU3ilAXBBSNm+rEYb7RjOLLHfcVrYmBeNh1pMIKG6v0LVfRYKUSAODIuJEFqLtjSNxZvnSTyzYUoY9h6zkUL8LlA5YDmJpLrzYnqjHll7BsEUCx5BSQkKETOT6O0Zi5NCdk43qHNz8Q3774KjUZbhrXHxaDjYHXHEXKWI7zt9FxyN5vQFekx9NxyN2mS+ekV/NxyN2vSXhDHzmMqL3Ul5sUaNMv9G3KwaFYRbZakwQuPB9vWVKHdDoheKWK44+IgCjInpKpFGj4bTSOn3Eg5vlJl/nZOz+4YYSbJogRs6jbIKRzljitNHVCGWbMKoRI7Dn1YUivvAW5RgGnE2Z6W/lDeHyPrmLMshCn3aRmITG/mYeWjTB2g1QrKjgSuYMJgmWK2X/WzmoIh1sOfrS1QtkcPzm8bb66at4Oj2EdIWXGrSe4GgH+bjPjnuf5TuuvApiX2MyzFWf5Nvcp+E7N8ACp62wMNA61xAuz/+0+ZXvGj3zFUOWUYtvkHLtMLba0042iNknVCeTcHAx+2Hwhfqivol5HcwvEv3Mq+uQn65yeIOMmGx4sPf8LvaVpM4GHh+4HsRAE7w4PAejPM65a/w3QRLQqK83xxV76eivHSnReYz6kSFYpxuqqN+fwBTcmfZn648vSqL62yYzauuYFr4tPa587P6+RaTs9s1puTrZ6Yy5mGLYg3M2fv0Y50/6VVLvASi3XdxJkurs95clHXS6rS+/9pnHhRO52//A2Yf0Pw=`

**Comment by tomcur** [comment]
Thanks for the report.

I just tried your save, and I'm able to level Vaagur to 133, instead of 130 you reported. Of course this is still not level 134. Another level in Vaagur would cost 1.773e40 HS, and the game says I have 1.773e40 HS left over, missing just a fraction of the total HS required.

The game is slightly less accurate than the calculator, so this is a rounding error on the game's side. Sadly I can't do much to fix it.
