### ISSUE TITLE
Can't load save file

### ISSUE THREAD

**Issue by Arcaxio** [Beskhue/ClickerHeroesCalculator#17]
When ever I push import, an error message keeps showing up, which says "Error : [Decimal Error] Invalid arguement : 1e18.8". Please help...

**Comment by tomcur** [comment]
Could you share your save file so I can debug this? If you use Reddit, you can send it to me at [/u/beskhue](https://www.reddit.com/user/beskhue).

**Comment by Arcaxio** [comment]
Sent on reddit

**Comment by tomcur** [comment]
The save file indicates it has been edited using a Clicker Heroes save editor.

On closer inspection, the `heroSoulsSacrificed` field has been set to `1e18.8`, which is an invalid value. This is either an error of the Clicker Heroes save editor, or an error of the user using such an editor. As such, the solution should be sought there.

**Comment by tomcur** [comment]
I've notified the creator of the save editor.
