### ISSUE TITLE
Caps

### ISSUE THREAD

**Issue by Gamesiarz** [Beskhue/ClickerHeroesCalculator#19]
Is there any chance to add caps for ancients? Even if I use "Ignore ancients that are minimized in-game" it still doesn't work well with hero souls

**Comment by tomcur** [comment]
Hey!

What do you mean exactly with "it still doesn't work well with hero souls"?

**Comment by Gamesiarz** [comment]
Well I just mean that this option is not optimal way for capping.  Chronos is a good example you could just add automatic cap for value where there is no point to still leveling particular ancients.

http://clickerheroes.wikia.com/wiki/Chronos,_Ancient_of_Time

**Comment by tomcur** [comment]
I agree. This is something I've wanted to implement for some time, but currently cannot work on this project.

Perhaps someone is willing to implement this.

Caps can be implemented in the models file. E.g. for Chronos a cap can be implemented here:
https://github.com/Beskhue/ClickerHeroesCalculator/blob/5efaabf7a13d1492782a17bf91d7ddcfdd34902a/calculator/js/data/model.js#L175-L183

**Comment by tomcur** [comment]
Implemented in 3afc5386955219b431cdca41c687be47d5297bd7.
