### ISSUE TITLE
different save format with the new Unity port of CH1

### ISSUE THREAD

**Issue by 3plus4i** [Beskhue/ClickerHeroesCalculator#20]
the new Unity port uses a different save format that calcs can't read yet, it will likely need adapting

https://clickerheroes.com/beta/

**Comment by dfederm** [comment]
I haven't played the game in a while. Are there any docs for the new format and examples to use?

**Comment by 3plus4i** [comment]
we didn't get official information about the save format yet, but someone just figured it out on the CH Discord server https://discord.com/channels/104739787872694272/234759114327195648/1013847810510160013

**Comment by dfederm** [comment]
Thanks, I'll try to take a look at this sometime this week.

**Comment by tomcur** [comment]
Thank you for the info! I'd be happy to merge a pull request and deploy a new version, but won't be working on patching the save format myself.

**Comment by dfederm** [comment]
(Woops, totally thought this was in the Clicker Heroes Tracker repo, not @tomcur's repo. Still, I'll look into it for Clicker Heroes Tracker)

**Comment by zuils10** [comment]
> Thank you for the info! I'd be happy to merge a pull request and deploy a new version, but won't be working on patching the save format myself.

I sent a pull request if you mind looking at it.

**Comment by tomcur** [comment]
Fixed by #21
