### ISSUE TITLE
Issue presenting large ancient change numbers

### ISSUE THREAD

**Issue by emiln** [Beskhue/ClickerHeroesCalculator#9]
Hi again, @Beskhue.

I'm not sure if I introduced it or not, but it seems the presentation of ancient change levels for copying isn't working so well for very large numbers:

![screenshot from 2016-12-26 14-53-47](https://cloud.githubusercontent.com/assets/1078925/21483000/e5f37522-cb7b-11e6-89a7-b54fe1b7e1ff.png)

At roughly `1e12` it starts formatting them in a way that can't be interpreted by the ClickerHeroes game. I'll have a go at solving it when I get back home to a tolerable computer, but it won't be for a few days.

**Comment by tomcur** [comment]
Thanks for the report. This output format should be understood by Clicker Heroes. For example, 123e2 would be interpreted (correctly) as 1.23e4. If you are having issues, please include screenshots from Clicker Heroes and please send me your save file.

**Comment by emiln** [comment]
Oh, that's actually really cool. I was quite certain I'd tried and failed pasting that format into the game client, but I'll double check at next ascension. You're probably right.

**Comment by emiln** [comment]
I just tried pasting in `1e12` and that definitely works. There's apparently no issue beyond my strange previous inability to make it work.

**Comment by tomcur** [comment]
Thanks for the update!
